version: "3"

services:
  localosmosis:
    build:
      context: .
      dockerfile: localnet/Dockerfile
      args:
        GIT_REF: "roman/sqs-poc-v20"
    container_name: localosmosis
    volumes:
      - $HOME/.localosmosisstate/:/osmosis/.osmosisd/
    ports:
      - 26657:26657
      - 1317:1317
      - 9090:9090
      - 9091:9091
      - 6060:6060

#  redis:
#    image: redis:latest
#    container_name: redis
#    restart: on-failure
#    ports:
#      - 6379:6379
#
#  sqs:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: sqs
#    environment:
#      DEBUG: "true"
#    volumes:
#      - ./config.json:/osmosis/config.json
#    restart: on-failure
#    depends_on:
#      - localosmosis
#      - redis
#    ports:
#      - 9092:9092
#
