name: SQS Integration Test

on:
  workflow_dispatch:
    inputs:
      sqs_endpoint: 
        description: 'Which sqs domain to test.'
        type: choice
        required: true
        default: 'false'
        # Note, stage is hardcoded in the test suite today.
        # We need to propagate the option to pytest.
        options: [ "https://sqs.stage.osmosis.zone"]

jobs:
  execute_sqs_integration_test:
    env:
      SQS_DOMAIN: "${{ github.event.inputs.sqs_endpoint }}"
    runs-on: self-hosted
    steps:
      - name: Checkout sqs repository
        uses: actions/checkout@v4
      - name: 🐍 Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
      - name: ⚡ Execute SQS Integration Test
        run:  |
          pytest -s -n auto
